CREATE TABLE BLOOD (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(3) NOT NULL
);

CREATE TABLE PATIENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PEOPLE_ID VARCHAR(8) NOT NULL,
    GENDER BOOLEAN NOT NULL,
    BLOOD INTEGER NOT NULL,
    BIRTHDATE DATE NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT 1
);

CREATE TABLE DOCTOR_SPECIFIC (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(32) NOT NULL
);

CREATE TABLE DOCTOR (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PREFIX_NAME VARCHAR(15) NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    DOCTOR_SPECIFIC_ID INTEGER NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT 1
);

CREATE TABLE MEDICINE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(64) NOT NULL,
    PRORERTY TEXT NOT NULL,
    PRICE REAL NOT NULL
);

CREATE TABLE DISPENSE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TREATMENT_ID INTEGER NOT NULL,
    MEDICINE_ID INTEGER NOT NULL,
    AMOUNT INTEGER NOT NULL,
    PRICE REAL NOT NULL
);

CREATE TABLE RECEIPT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TREATMENT_ID INTEGER NOT NULL,
    PEOPLE_ID INTEGER NOT NULL,
    PRICE FLOAT NOT NULL,
    IS_PAY BOOLEAN DEFAULT 0
);

CREATE TABLE TREATMENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DOCTOR_ID INTEGER NOT NULL,
    PEOPLE_ID INTEGER NOT NULL,
    BEHAVIOUR TEXT NOT NULL,
    PRESSURE_HIGHT INTEGER NOT NULL,
    PRESSURE_LOW INTEGER NOT NULL,
    IS_FIN BOOLEAN DEFAULT 0,
    RECEIPT_ID INTEGER DEFAULT 0,
    TREATMENT_DATE DATETIME NOT NULL
);
