CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE BLOOD (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(3) NOT NULL UNIQUE
);
CREATE TABLE MEDICINE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(64) NOT NULL UNIQUE,
    PRICE REAL NOT NULL
);
CREATE TABLE DISPENSE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TREATMENT_ID INTEGER NOT NULL,
    MEDICINE_ID INTEGER NOT NULL,
    AMOUNT INTEGER NOT NULL,
    PRICE REAL NOT NULL
);
CREATE TABLE RECEIPT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TREATMENT_ID INTEGER NOT NULL UNIQUE,
    PRICE REAL NOT NULL,
    IS_PAY BOOLEAN DEFAULT 0
);
CREATE TABLE DOCTOR (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PREFIX_NAME VARCHAR(15) NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    DOCTOR_SPECIFIC_ID INTEGER NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT 1,
    UNIQUE (FIRST_NAME, LAST_NAME)
);
CREATE TABLE DOCTOR_SPECIFIC (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(32) NOT NULL UNIQUE
);
CREATE TABLE TREATMENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DOCTOR_ID INTEGER NOT NULL,
    PEOPLE_ID VARCHAR(13) NOT NULL,
    BEHAVIOUR TEXT NOT NULL,
    PRESSURE_HIGHT INTEGER NOT NULL,
    PRESSURE_LOW INTEGER NOT NULL,
    TREATMENT_DATE DATETIME NOT NULL,
    HEIGHT REAL NOT NULL,
    WEIGHT REAL NOT NULL
);
CREATE TABLE PATIENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PEOPLE_ID VARCHAR(13) NOT NULL UNIQUE,
    GENDER BOOLEAN NOT NULL,
    BLOOD_ID INTEGER NOT NULL,
    CLASH TEXT,
    BIRTHDATE DATE NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT 1
);
